CC=gcc
LIBS=-lpthread
FLAGS=-Wall

TARGETS=1.1 1.2a-b 1.2c 1.2d 1.2e 1.2f 1.3a 1.3b 1.4a 1.4b 1.4c 1.5a 1.5b

all: $(TARGETS)

1.1:
	$(CC) $(FLAGS) -o 1.1 1.1.c $(LIBS)

1.2a-b:
	$(CC) $(FLAGS) -o 1.2a-b 1.2a-b.c $(LIBS)

1.2c:
	$(CC) $(FLAGS) -o 1.2c 1.2c.c $(LIBS)

1.2d:
	$(CC) $(FLAGS) -o 1.2d 1.2d.c $(LIBS)

1.2e:
	$(CC) $(FLAGS) -o 1.2e 1.2e.c $(LIBS)

1.2f:
	$(CC) $(FLAGS) -o 1.2f 1.2f.c $(LIBS)

1.3a:
	$(CC) $(FLAGS) -o 1.3a 1.3a.c $(LIBS)

1.3b:
	$(CC) $(FLAGS) -o 1.3b 1.3b.c $(LIBS)

1.4a:
	$(CC) $(FLAGS) -o 1.4a 1.4a.c $(LIBS)

1.4b:
	$(CC) $(FLAGS) -o 1.4b 1.4b.c $(LIBS)

1.4c:
	$(CC) $(FLAGS) -o 1.4c 1.4c.c $(LIBS)

1.5a:
	$(CC) $(FLAGS) -o 1.5a 1.5a.c $(LIBS)

1.5b:
	$(CC) $(FLAGS) -o 1.5b 1.5b.c $(LIBS)


clean:
	rm $(TARGETS)
